language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
notifications:
  email: false
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $firebase_token
  local_dir: build
    on:
      branch: master
